"""initial schema 18 core tables

Revision ID: ad22105850f7
Revises:
Create Date: 2026-05-27 05:46:29.208327+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad22105850f7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "stores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("google_place_id", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("opened_on", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(), server_default="Asia/Taipei", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stores_tenant_active", "stores", ["tenant_id", "is_active"], unique=False)
    op.create_index(op.f("ix_stores_tenant_id"), "stores", ["tenant_id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "MANAGER",
                "CHEF",
                "STAFF",
                "PARTTIME",
                name="employee_role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("hourly_wage", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("monthly_salary", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("hired_on", sa.Date(), nullable=False),
        sa.Column("terminated_on", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_store_id"), "employees", ["store_id"], unique=False)
    op.create_index(op.f("ix_employees_tenant_id"), "employees", ["tenant_id"], unique=False)
    op.create_index(
        "ix_employees_tenant_store", "employees", ["tenant_id", "store_id"], unique=False
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column(
            "standard_cost_per_unit",
            sa.Numeric(precision=14, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column("reorder_threshold", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_store_id"), "ingredients", ["store_id"], unique=False)
    op.create_index(op.f("ix_ingredients_tenant_id"), "ingredients", ["tenant_id"], unique=False)
    op.create_index(
        "ix_ingredients_tenant_store_active",
        "ingredients",
        ["tenant_id", "store_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "menu_categories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menu_categories_store_id"), "menu_categories", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_categories_tenant_id"), "menu_categories", ["tenant_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("order_no", sa.Text(), nullable=False),
        sa.Column("business_date", sa.Date(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "VOIDED",
                "REFUNDED",
                name="order_status",
                native_enum=False,
                length=16,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("invoice_number", sa.Text(), nullable=True),
        sa.Column("carrier_type", sa.Text(), nullable=True),
        sa.Column("carrier_id", sa.Text(), nullable=True),
        sa.Column("buyer_tax_id", sa.Text(), nullable=True),
        sa.Column("external_pos_id", sa.Text(), nullable=True),
        sa.Column("pos_source", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_business_date"), "orders", ["business_date"], unique=False)
    op.create_index(
        "ix_orders_store_business_date", "orders", ["store_id", "business_date"], unique=False
    )
    op.create_index(op.f("ix_orders_store_id"), "orders", ["store_id"], unique=False)
    op.create_index(op.f("ix_orders_tenant_id"), "orders", ["tenant_id"], unique=False)
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column(
            "leave_type",
            sa.Enum(
                "ANNUAL",
                "PERSONAL",
                "SICK",
                "WEDDING",
                "BEREAVEMENT",
                "MATERNITY",
                "MENSTRUAL",
                "OFFICIAL",
                "OTHER",
                name="leave_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="leave_status",
                native_enum=False,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_requests_employee_id"), "leave_requests", ["employee_id"], unique=False
    )
    op.create_index(
        "ix_leave_requests_employee_start",
        "leave_requests",
        ["employee_id", "start_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_tenant_id"), "leave_requests", ["tenant_id"], unique=False
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost_estimate", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("external_pos_id", sa.Text(), nullable=True),
        sa.Column("pos_source", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["menu_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menu_items_category_id"), "menu_items", ["category_id"], unique=False)
    op.create_index(op.f("ix_menu_items_store_id"), "menu_items", ["store_id"], unique=False)
    op.create_index(op.f("ix_menu_items_tenant_id"), "menu_items", ["tenant_id"], unique=False)
    op.create_index(
        "ix_menu_items_tenant_store_available",
        "menu_items",
        ["tenant_id", "store_id", "is_available"],
        unique=False,
    )
    op.create_index(
        "uq_menu_items_tenant_sku_live",
        "menu_items",
        ["tenant_id", "sku"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "order_discounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PERCENT",
                "AMOUNT",
                "COMP",
                "ALLOWANCE",
                "EMPLOYEE",
                name="order_discount_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("applied_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["applied_by"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_discounts_order_id"), "order_discounts", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_discounts_tenant_id"), "order_discounts", ["tenant_id"], unique=False
    )
    op.create_table(
        "order_payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "CASH",
                "CREDIT",
                "LINEPAY",
                "APPLEPAY",
                "JKO",
                "UBEREATS",
                "FOODPANDA",
                "VOUCHER",
                "OTHER",
                name="order_payment_method",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "fee_amount", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column(
            "paid_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_order_payments_method_paid_at", "order_payments", ["method", "paid_at"], unique=False
    )
    op.create_index(
        op.f("ix_order_payments_order_id"), "order_payments", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_payments_tenant_id"), "order_payments", ["tenant_id"], unique=False
    )
    op.create_table(
        "shifts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("role_hint", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shifts_employee_id"), "shifts", ["employee_id"], unique=False)
    op.create_index(
        "ix_shifts_employee_start", "shifts", ["employee_id", "scheduled_start"], unique=False
    )
    op.create_index(op.f("ix_shifts_store_id"), "shifts", ["store_id"], unique=False)
    op.create_index(
        "ix_shifts_store_start", "shifts", ["store_id", "scheduled_start"], unique=False
    )
    op.create_index(op.f("ix_shifts_tenant_id"), "shifts", ["tenant_id"], unique=False)
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column(
            "movement_type",
            sa.Enum(
                "PURCHASE",
                "SALE_CONSUME",
                "ADJUSTMENT_IN",
                "ADJUSTMENT_OUT",
                "WASTE",
                "STAFF_MEAL",
                "TASTING",
                "EXPIRY",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                name="stock_movement_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("qty", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("source_table", sa.Text(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_ingredient_id"), "stock_movements", ["ingredient_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_ingredient_time",
        "stock_movements",
        ["ingredient_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_store_id"), "stock_movements", ["store_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_store_time",
        "stock_movements",
        ["store_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_tenant_id"), "stock_movements", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_type_time",
        "stock_movements",
        ["store_id", "movement_type", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "time_clocks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("clock_in", sa.DateTime(timezone=True), nullable=False),
        sa.Column("clock_out", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "regular_hours", sa.Numeric(precision=6, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "overtime_tier1_hours",
            sa.Numeric(precision=6, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "overtime_tier2_hours",
            sa.Numeric(precision=6, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "holiday_hours", sa.Numeric(precision=6, scale=2), server_default="0", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_clocks_employee_id"), "time_clocks", ["employee_id"], unique=False
    )
    op.create_index(
        "ix_time_clocks_employee_in", "time_clocks", ["employee_id", "clock_in"], unique=False
    )
    op.create_index(op.f("ix_time_clocks_store_id"), "time_clocks", ["store_id"], unique=False)
    op.create_index(
        "ix_time_clocks_store_in", "time_clocks", ["store_id", "clock_in"], unique=False
    )
    op.create_index(op.f("ix_time_clocks_tenant_id"), "time_clocks", ["tenant_id"], unique=False)
    op.create_table(
        "waste_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reported_by", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reported_by"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_waste_events_ingredient_id"), "waste_events", ["ingredient_id"], unique=False
    )
    op.create_index(op.f("ix_waste_events_store_id"), "waste_events", ["store_id"], unique=False)
    op.create_index(
        "ix_waste_events_store_occurred", "waste_events", ["store_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_waste_events_tenant_id"), "waste_events", ["tenant_id"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("cogs_actual", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("cogs_theoretical", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_lines_menu_item_id"), "order_lines", ["menu_item_id"], unique=False
    )
    op.create_index(op.f("ix_order_lines_order_id"), "order_lines", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_lines_tenant_id"), "order_lines", ["tenant_id"], unique=False)
    op.create_table(
        "recipes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_id", sa.UUID(), nullable=False),
        sa.Column("qty_per_serving", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "effective_from", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False
        ),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_ingredient_id"), "recipes", ["ingredient_id"], unique=False)
    op.create_index(op.f("ix_recipes_menu_item_id"), "recipes", ["menu_item_id"], unique=False)
    op.create_index(op.f("ix_recipes_tenant_id"), "recipes", ["tenant_id"], unique=False)
    op.create_index(
        "uq_recipes_current",
        "recipes",
        ["menu_item_id", "ingredient_id"],
        unique=True,
        postgresql_where=sa.text("effective_to IS NULL"),
    )
    op.create_table(
        "staff_meal_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=True),
        sa.Column("ingredients_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_staff_meal_events_employee_id"), "staff_meal_events", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_staff_meal_events_store_id"), "staff_meal_events", ["store_id"], unique=False
    )
    op.create_index(
        "ix_staff_meal_events_store_occurred",
        "staff_meal_events",
        ["store_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_staff_meal_events_tenant_id"), "staff_meal_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "tasting_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasting_events_store_id"), "tasting_events", ["store_id"], unique=False
    )
    op.create_index(
        "ix_tasting_events_store_occurred",
        "tasting_events",
        ["store_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasting_events_tenant_id"), "tasting_events", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasting_events_tenant_id"), table_name="tasting_events")
    op.drop_index("ix_tasting_events_store_occurred", table_name="tasting_events")
    op.drop_index(op.f("ix_tasting_events_store_id"), table_name="tasting_events")
    op.drop_table("tasting_events")
    op.drop_index(op.f("ix_staff_meal_events_tenant_id"), table_name="staff_meal_events")
    op.drop_index("ix_staff_meal_events_store_occurred", table_name="staff_meal_events")
    op.drop_index(op.f("ix_staff_meal_events_store_id"), table_name="staff_meal_events")
    op.drop_index(op.f("ix_staff_meal_events_employee_id"), table_name="staff_meal_events")
    op.drop_table("staff_meal_events")
    op.drop_index(
        "uq_recipes_current", table_name="recipes", postgresql_where=sa.text("effective_to IS NULL")
    )
    op.drop_index(op.f("ix_recipes_tenant_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_menu_item_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_ingredient_id"), table_name="recipes")
    op.drop_table("recipes")
    op.drop_index(op.f("ix_order_lines_tenant_id"), table_name="order_lines")
    op.drop_index(op.f("ix_order_lines_order_id"), table_name="order_lines")
    op.drop_index(op.f("ix_order_lines_menu_item_id"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index(op.f("ix_waste_events_tenant_id"), table_name="waste_events")
    op.drop_index("ix_waste_events_store_occurred", table_name="waste_events")
    op.drop_index(op.f("ix_waste_events_store_id"), table_name="waste_events")
    op.drop_index(op.f("ix_waste_events_ingredient_id"), table_name="waste_events")
    op.drop_table("waste_events")
    op.drop_index(op.f("ix_time_clocks_tenant_id"), table_name="time_clocks")
    op.drop_index("ix_time_clocks_store_in", table_name="time_clocks")
    op.drop_index(op.f("ix_time_clocks_store_id"), table_name="time_clocks")
    op.drop_index("ix_time_clocks_employee_in", table_name="time_clocks")
    op.drop_index(op.f("ix_time_clocks_employee_id"), table_name="time_clocks")
    op.drop_table("time_clocks")
    op.drop_index("ix_stock_movements_type_time", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_tenant_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_store_time", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_store_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_ingredient_time", table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_ingredient_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_shifts_tenant_id"), table_name="shifts")
    op.drop_index("ix_shifts_store_start", table_name="shifts")
    op.drop_index(op.f("ix_shifts_store_id"), table_name="shifts")
    op.drop_index("ix_shifts_employee_start", table_name="shifts")
    op.drop_index(op.f("ix_shifts_employee_id"), table_name="shifts")
    op.drop_table("shifts")
    op.drop_index(op.f("ix_order_payments_tenant_id"), table_name="order_payments")
    op.drop_index(op.f("ix_order_payments_order_id"), table_name="order_payments")
    op.drop_index("ix_order_payments_method_paid_at", table_name="order_payments")
    op.drop_table("order_payments")
    op.drop_index(op.f("ix_order_discounts_tenant_id"), table_name="order_discounts")
    op.drop_index(op.f("ix_order_discounts_order_id"), table_name="order_discounts")
    op.drop_table("order_discounts")
    op.drop_index(
        "uq_menu_items_tenant_sku_live",
        table_name="menu_items",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_menu_items_tenant_store_available", table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_tenant_id"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_store_id"), table_name="menu_items")
    op.drop_index(op.f("ix_menu_items_category_id"), table_name="menu_items")
    op.drop_table("menu_items")
    op.drop_index(op.f("ix_leave_requests_tenant_id"), table_name="leave_requests")
    op.drop_index("ix_leave_requests_employee_start", table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_employee_id"), table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_orders_tenant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_store_id"), table_name="orders")
    op.drop_index("ix_orders_store_business_date", table_name="orders")
    op.drop_index(op.f("ix_orders_business_date"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_menu_categories_tenant_id"), table_name="menu_categories")
    op.drop_index(op.f("ix_menu_categories_store_id"), table_name="menu_categories")
    op.drop_table("menu_categories")
    op.drop_index("ix_ingredients_tenant_store_active", table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_tenant_id"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_store_id"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index("ix_employees_tenant_store", table_name="employees")
    op.drop_index(op.f("ix_employees_tenant_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_store_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_stores_tenant_id"), table_name="stores")
    op.drop_index("ix_stores_tenant_active", table_name="stores")
    op.drop_table("stores")
    op.drop_table("tenants")
    # ### end Alembic commands ###
