"""ugc submissions

Revision ID: 41772db92af3
Revises: f90aaf62e51c
Create Date: 2026-06-19 21:50:40.762432+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41772db92af3"
down_revision: str | Sequence[str] | None = "f90aaf62e51c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ugc_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "GOOGLE_REVIEW", "IG_POST", "CHECKIN", name="ugc_kind", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("proof_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", name="ugc_status", native_enum=False, length=16
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "reward_points", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ugc_customer_time", "ugc_submissions", ["customer_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ugc_submissions_customer_id"), "ugc_submissions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_ugc_submissions_tenant_id"), "ugc_submissions", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_ugc_tenant_status", "ugc_submissions", ["tenant_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ugc_tenant_status", table_name="ugc_submissions")
    op.drop_index(op.f("ix_ugc_submissions_tenant_id"), table_name="ugc_submissions")
    op.drop_index(op.f("ix_ugc_submissions_customer_id"), table_name="ugc_submissions")
    op.drop_index("ix_ugc_customer_time", table_name="ugc_submissions")
    op.drop_table("ugc_submissions")
    # ### end Alembic commands ###
