"""modifier groups, combo components, kitchen auto-routing

Revision ID: 8476617278b8
Revises: f73434f99a7a
Create Date: 2026-07-14 13:26:11.238621+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8476617278b8"
down_revision: str | Sequence[str] | None = "f73434f99a7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "combo_components",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("combo_item_id", sa.UUID(), nullable=False),
        sa.Column("component_item_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Numeric(precision=12, scale=4), server_default="1", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["combo_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["component_item_id"], ["menu_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_combo_components_combo_item_id"),
        "combo_components",
        ["combo_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_combo_components_component_item_id"),
        "combo_components",
        ["component_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_combo_components_tenant_id"), "combo_components", ["tenant_id"], unique=False
    )
    op.create_table(
        "modifier_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("min_select", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_select", sa.Integer(), server_default="1", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modifier_groups_menu_item_id"), "modifier_groups", ["menu_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_modifier_groups_tenant_id"), "modifier_groups", ["tenant_id"], unique=False
    )
    op.create_table(
        "modifier_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "price_delta", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["modifier_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modifier_options_group_id"), "modifier_options", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_modifier_options_tenant_id"), "modifier_options", ["tenant_id"], unique=False
    )
    op.create_table(
        "order_line_modifiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("modifier_option_id", sa.UUID(), nullable=False),
        sa.Column("option_name", sa.Text(), nullable=False),
        sa.Column("price_delta", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["modifier_option_id"], ["modifier_options.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["order_line_id"], ["order_lines.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_line_modifiers_modifier_option_id"),
        "order_line_modifiers",
        ["modifier_option_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_line_modifiers_order_line_id"),
        "order_line_modifiers",
        ["order_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_line_modifiers_tenant_id"),
        "order_line_modifiers",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "menu_items",
        sa.Column(
            "default_kitchen_station",
            sa.Enum(
                "KITCHEN",
                "BAR",
                "DESSERT",
                "COUNTER",
                name="kitchen_station",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column("order_lines", sa.Column("combo_parent_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_order_lines_combo_parent_id"), "order_lines", ["combo_parent_id"], unique=False
    )
    op.create_foreign_key(
        "fk_order_lines_combo_parent_id_order_lines",
        "order_lines",
        "order_lines",
        ["combo_parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_order_lines_combo_parent_id_order_lines", "order_lines", type_="foreignkey"
    )
    op.drop_index(op.f("ix_order_lines_combo_parent_id"), table_name="order_lines")
    op.drop_column("order_lines", "combo_parent_id")
    op.drop_column("menu_items", "default_kitchen_station")
    op.drop_index(op.f("ix_order_line_modifiers_tenant_id"), table_name="order_line_modifiers")
    op.drop_index(op.f("ix_order_line_modifiers_order_line_id"), table_name="order_line_modifiers")
    op.drop_index(
        op.f("ix_order_line_modifiers_modifier_option_id"), table_name="order_line_modifiers"
    )
    op.drop_table("order_line_modifiers")
    op.drop_index(op.f("ix_modifier_options_tenant_id"), table_name="modifier_options")
    op.drop_index(op.f("ix_modifier_options_group_id"), table_name="modifier_options")
    op.drop_table("modifier_options")
    op.drop_index(op.f("ix_modifier_groups_tenant_id"), table_name="modifier_groups")
    op.drop_index(op.f("ix_modifier_groups_menu_item_id"), table_name="modifier_groups")
    op.drop_table("modifier_groups")
    op.drop_index(op.f("ix_combo_components_tenant_id"), table_name="combo_components")
    op.drop_index(op.f("ix_combo_components_component_item_id"), table_name="combo_components")
    op.drop_index(op.f("ix_combo_components_combo_item_id"), table_name="combo_components")
    op.drop_table("combo_components")
    # ### end Alembic commands ###
