"""add_customer_id_to_orders

Revision ID: d5ddbc204c88
Revises: 0b230fe61411
Create Date: 2026-06-06 00:42:07.086452+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5ddbc204c88"
down_revision: str | Sequence[str] | None = "0b230fe61411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("customer_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_foreign_key(None, "orders", "customers", ["customer_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_column("orders", "customer_id")
    # ### end Alembic commands ###
