"""launch wheel campaign engine

Revision ID: 485b908ca19c
Revises: d5ddbc204c88
Create Date: 2026-06-17 13:46:27.955561+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "485b908ca19c"
down_revision: str | Sequence[str] | None = "d5ddbc204c88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marketing_campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PAUSED",
                "ENDED",
                name="campaign_status",
                native_enum=False,
                length=16,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("daily_spin_limit", sa.Integer(), server_default="1", nullable=False),
        sa.Column("voucher_start_offset_days", sa.Integer(), server_default="0", nullable=False),
        sa.Column("voucher_validity_days", sa.Integer(), server_default="14", nullable=False),
        sa.Column("daily_message", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_campaigns_tenant_status", "marketing_campaigns", ["tenant_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_marketing_campaigns_store_id"), "marketing_campaigns", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_marketing_campaigns_tenant_id"), "marketing_campaigns", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_campaigns_tenant_slug_live",
        "marketing_campaigns",
        ["tenant_id", "slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "campaign_prizes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("weight", sa.Integer(), server_default="1", nullable=False),
        sa.Column("menu_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "value_estimate", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("total_quota", sa.Integer(), nullable=True),
        sa.Column("daily_quota", sa.Integer(), nullable=True),
        sa.Column("awarded_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["marketing_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_prizes_campaign_id"), "campaign_prizes", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_prizes_menu_item_id"), "campaign_prizes", ["menu_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_prizes_tenant_id"), "campaign_prizes", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_prizes_campaign_active", "campaign_prizes", ["campaign_id", "is_active"], unique=False
    )
    op.create_table(
        "campaign_spins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("prize_id", sa.UUID(), nullable=True),
        sa.Column("spin_date", sa.Date(), nullable=False),
        sa.Column("won", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["marketing_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["prize_id"], ["campaign_prizes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_spins_campaign_id"), "campaign_spins", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_spins_customer_id"), "campaign_spins", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_spins_prize_id"), "campaign_spins", ["prize_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_spins_tenant_id"), "campaign_spins", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_spins_campaign_customer_date",
        "campaign_spins",
        ["campaign_id", "customer_id", "spin_date"],
        unique=False,
    )
    op.create_index(
        "ix_spins_prize_date", "campaign_spins", ["prize_id", "spin_date"], unique=False
    )
    op.create_table(
        "campaign_vouchers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("prize_id", sa.UUID(), nullable=False),
        sa.Column("spin_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "REDEEMED",
                "EXPIRED",
                "VOID",
                name="voucher_status",
                native_enum=False,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("prize_name", sa.String(length=120), nullable=False),
        sa.Column(
            "value_estimate", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("menu_item_id", sa.UUID(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redeemed_on", sa.Date(), nullable=True),
        sa.Column("redeemed_order_id", sa.UUID(), nullable=True),
        sa.Column("redeemed_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["marketing_campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["prize_id"], ["campaign_prizes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["redeemed_by"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["redeemed_order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["spin_id"], ["campaign_spins.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_vouchers_campaign_id"), "campaign_vouchers", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_vouchers_customer_id"), "campaign_vouchers", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_vouchers_menu_item_id"),
        "campaign_vouchers",
        ["menu_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_vouchers_prize_id"), "campaign_vouchers", ["prize_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_vouchers_redeemed_order_id"),
        "campaign_vouchers",
        ["redeemed_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_vouchers_spin_id"), "campaign_vouchers", ["spin_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_vouchers_tenant_id"), "campaign_vouchers", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_vouchers_campaign_status", "campaign_vouchers", ["campaign_id", "status"], unique=False
    )
    op.create_index(
        "ix_vouchers_customer_campaign",
        "campaign_vouchers",
        ["customer_id", "campaign_id"],
        unique=False,
    )
    op.create_index(
        "uq_vouchers_one_redeem_per_day",
        "campaign_vouchers",
        ["campaign_id", "customer_id", "redeemed_on"],
        unique=True,
        postgresql_where=sa.text("redeemed_on IS NOT NULL"),
    )
    op.create_index(
        "uq_vouchers_tenant_code", "campaign_vouchers", ["tenant_id", "code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_vouchers_tenant_code", table_name="campaign_vouchers")
    op.drop_index(
        "uq_vouchers_one_redeem_per_day",
        table_name="campaign_vouchers",
        postgresql_where=sa.text("redeemed_on IS NOT NULL"),
    )
    op.drop_index("ix_vouchers_customer_campaign", table_name="campaign_vouchers")
    op.drop_index("ix_vouchers_campaign_status", table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_tenant_id"), table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_spin_id"), table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_redeemed_order_id"), table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_prize_id"), table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_menu_item_id"), table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_customer_id"), table_name="campaign_vouchers")
    op.drop_index(op.f("ix_campaign_vouchers_campaign_id"), table_name="campaign_vouchers")
    op.drop_table("campaign_vouchers")
    op.drop_index("ix_spins_prize_date", table_name="campaign_spins")
    op.drop_index("ix_spins_campaign_customer_date", table_name="campaign_spins")
    op.drop_index(op.f("ix_campaign_spins_tenant_id"), table_name="campaign_spins")
    op.drop_index(op.f("ix_campaign_spins_prize_id"), table_name="campaign_spins")
    op.drop_index(op.f("ix_campaign_spins_customer_id"), table_name="campaign_spins")
    op.drop_index(op.f("ix_campaign_spins_campaign_id"), table_name="campaign_spins")
    op.drop_table("campaign_spins")
    op.drop_index("ix_prizes_campaign_active", table_name="campaign_prizes")
    op.drop_index(op.f("ix_campaign_prizes_tenant_id"), table_name="campaign_prizes")
    op.drop_index(op.f("ix_campaign_prizes_menu_item_id"), table_name="campaign_prizes")
    op.drop_index(op.f("ix_campaign_prizes_campaign_id"), table_name="campaign_prizes")
    op.drop_table("campaign_prizes")
    op.drop_index(
        "uq_campaigns_tenant_slug_live",
        table_name="marketing_campaigns",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_marketing_campaigns_tenant_id"), table_name="marketing_campaigns")
    op.drop_index(op.f("ix_marketing_campaigns_store_id"), table_name="marketing_campaigns")
    op.drop_index("ix_campaigns_tenant_status", table_name="marketing_campaigns")
    op.drop_table("marketing_campaigns")
    # ### end Alembic commands ###
