"""odoo sync dead-letter state on purchase_orders

Revision ID: 938b0ab19f78
Revises: 8307a94acb62
Create Date: 2026-07-29 15:31:12.560822+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "938b0ab19f78"
down_revision: str | Sequence[str] | None = "8307a94acb62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_orders",
        sa.Column("odoo_sync_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("purchase_orders", sa.Column("odoo_last_sync_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_orders", "odoo_last_sync_error")
    op.drop_column("purchase_orders", "odoo_sync_attempts")
    # ### end Alembic commands ###
