"""referral flywheel

Revision ID: f90aaf62e51c
Revises: 9511ce867866
Create Date: 2026-06-19 21:43:54.108872+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f90aaf62e51c"
down_revision: str | Sequence[str] | None = "9511ce867866"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_id", sa.UUID(), nullable=False),
        sa.Column("referred_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "QUALIFIED", name="referral_status", native_enum=False, length=16),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("qualifying_order_id", sa.UUID(), nullable=True),
        sa.Column(
            "referrer_reward_points",
            sa.Numeric(precision=14, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column("qualified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["qualifying_order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referred_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referrer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrals_referrer_id"), "referrals", ["referrer_id"], unique=False)
    op.create_index("ix_referrals_status", "referrals", ["status"], unique=False)
    op.create_index(op.f("ix_referrals_tenant_id"), "referrals", ["tenant_id"], unique=False)
    op.create_index("uq_referrals_referred", "referrals", ["referred_id"], unique=True)
    op.add_column("customers", sa.Column("referral_code", sa.String(length=16), nullable=True))
    op.create_index(
        "uq_customers_referral_code",
        "customers",
        ["tenant_id", "referral_code"],
        unique=True,
        postgresql_where="referral_code IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_customers_referral_code",
        table_name="customers",
        postgresql_where="referral_code IS NOT NULL",
    )
    op.drop_column("customers", "referral_code")
    op.drop_index("uq_referrals_referred", table_name="referrals")
    op.drop_index(op.f("ix_referrals_tenant_id"), table_name="referrals")
    op.drop_index("ix_referrals_status", table_name="referrals")
    op.drop_index(op.f("ix_referrals_referrer_id"), table_name="referrals")
    op.drop_table("referrals")
    # ### end Alembic commands ###
