"""dining tables + table sessions + order pos columns

Revision ID: 20b062b46d2c
Revises: 41772db92af3
Create Date: 2026-07-09 16:02:29.921496+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20b062b46d2c"
down_revision: str | Sequence[str] | None = "41772db92af3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dining_tables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("zone", sa.Text(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("qr_token", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qr_token"),
    )
    op.create_index(op.f("ix_dining_tables_store_id"), "dining_tables", ["store_id"], unique=False)
    op.create_index(
        op.f("ix_dining_tables_tenant_id"), "dining_tables", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_dining_tables_store_name_live",
        "dining_tables",
        ["store_id", "name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "table_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CANCELLED",
                name="table_session_status",
                native_enum=False,
                length=16,
            ),
            # SQLEnum(native_enum=False) stores the member NAME, so defaults
            # and index predicates use "OPEN", not "open".
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_by", sa.UUID(), nullable=True),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["opened_by"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reservation_id"], ["reservations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["table_id"], ["dining_tables.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_table_sessions_store_id"), "table_sessions", ["store_id"], unique=False
    )
    op.create_index(
        "ix_table_sessions_store_status", "table_sessions", ["store_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_table_sessions_table_id"), "table_sessions", ["table_id"], unique=False
    )
    op.create_index(
        op.f("ix_table_sessions_tenant_id"), "table_sessions", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_table_sessions_one_open_per_table",
        "table_sessions",
        ["table_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.add_column(
        "orders",
        sa.Column(
            "order_type",
            sa.Enum(
                "DINE_IN", "TAKEOUT", "DELIVERY", name="order_type", native_enum=False, length=16
            ),
            server_default="DINE_IN",
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "channel",
            sa.Enum(
                "POS",
                "TABLE_QR",
                "TABLET",
                "ONLINE",
                "EXTERNAL",
                name="order_channel",
                native_enum=False,
                length=16,
            ),
            server_default="EXTERNAL",
            nullable=False,
        ),
    )
    op.add_column("orders", sa.Column("table_session_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_orders_table_session_id"), "orders", ["table_session_id"], unique=False
    )
    op.create_foreign_key(
        "fk_orders_table_session_id",
        "orders",
        "table_sessions",
        ["table_session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_orders_table_session_id", "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_table_session_id"), table_name="orders")
    op.drop_column("orders", "table_session_id")
    op.drop_column("orders", "channel")
    op.drop_column("orders", "order_type")
    op.drop_index(
        "uq_table_sessions_one_open_per_table",
        table_name="table_sessions",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(op.f("ix_table_sessions_tenant_id"), table_name="table_sessions")
    op.drop_index(op.f("ix_table_sessions_table_id"), table_name="table_sessions")
    op.drop_index("ix_table_sessions_store_status", table_name="table_sessions")
    op.drop_index(op.f("ix_table_sessions_store_id"), table_name="table_sessions")
    op.drop_table("table_sessions")
    op.drop_index(
        "uq_dining_tables_store_name_live",
        table_name="dining_tables",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_dining_tables_tenant_id"), table_name="dining_tables")
    op.drop_index(op.f("ix_dining_tables_store_id"), table_name="dining_tables")
    op.drop_table("dining_tables")
    # ### end Alembic commands ###
