"""orders service_charge_rate

Revision ID: f73434f99a7a
Revises: 87ef29f6e7bb
Create Date: 2026-07-14 05:05:20.243574+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f73434f99a7a"
down_revision: str | Sequence[str] | None = "87ef29f6e7bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "service_charge_rate",
            sa.Numeric(precision=5, scale=4),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "service_charge_rate")
    # ### end Alembic commands ###
