"""menu item availability window for time-based menus

Revision ID: 729ce3d4540c
Revises: 8476617278b8
Create Date: 2026-07-14 14:10:42.549274+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "729ce3d4540c"
down_revision: str | Sequence[str] | None = "8476617278b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("menu_items", sa.Column("available_start_time", sa.Time(), nullable=True))
    op.add_column("menu_items", sa.Column("available_end_time", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_items", "available_end_time")
    op.drop_column("menu_items", "available_start_time")
    # ### end Alembic commands ###
