"""online takeout pickup time and queue preorder link

Revision ID: 5603cb48bb78
Revises: 729ce3d4540c
Create Date: 2026-07-14 14:34:02.596040+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5603cb48bb78"
down_revision: str | Sequence[str] | None = "729ce3d4540c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("pickup_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("walk_in_queue", sa.Column("order_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_walk_in_queue_order_id_orders",
        "walk_in_queue",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_walk_in_queue_order_id_orders", "walk_in_queue", type_="foreignkey")
    op.drop_column("walk_in_queue", "order_id")
    op.drop_column("orders", "pickup_at")
    # ### end Alembic commands ###
