"""kds reservations queue

Revision ID: de4a293237b8
Revises: 6c120a022a19
Create Date: 2026-05-27 09:32:55.284211+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de4a293237b8"
down_revision: str | Sequence[str] | None = "6c120a022a19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("contact_name", sa.String(length=80), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("reserved_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "BOOKED",
                "CONFIRMED",
                "SEATED",
                "COMPLETED",
                "NO_SHOW",
                "CANCELLED",
                name="reservation_status",
                native_enum=False,
                length=16,
            ),
            server_default="booked",
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("deposit_amount", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reservations_customer_id"), "reservations", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_reservations_reserved_for"), "reservations", ["reserved_for"], unique=False
    )
    op.create_index(
        "ix_reservations_status_time", "reservations", ["status", "reserved_for"], unique=False
    )
    op.create_index(op.f("ix_reservations_store_id"), "reservations", ["store_id"], unique=False)
    op.create_index(
        "ix_reservations_store_time", "reservations", ["store_id", "reserved_for"], unique=False
    )
    op.create_index(op.f("ix_reservations_tenant_id"), "reservations", ["tenant_id"], unique=False)
    op.create_table(
        "walk_in_queue",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("contact_name", sa.String(length=80), nullable=False),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("queue_no", sa.String(length=16), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "CALLED",
                "SEATED",
                "ABANDONED",
                name="queue_status",
                native_enum=False,
                length=16,
            ),
            server_default="waiting",
            nullable=False,
        ),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_queue_store_status", "walk_in_queue", ["store_id", "status", "joined_at"], unique=False
    )
    op.create_index(
        op.f("ix_walk_in_queue_customer_id"), "walk_in_queue", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_walk_in_queue_store_id"), "walk_in_queue", ["store_id"], unique=False)
    op.create_index(
        op.f("ix_walk_in_queue_tenant_id"), "walk_in_queue", ["tenant_id"], unique=False
    )
    op.add_column(
        "order_lines",
        sa.Column(
            "kitchen_station",
            sa.Enum(
                "KITCHEN",
                "BAR",
                "DESSERT",
                "COUNTER",
                name="kitchen_station",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "order_lines",
        sa.Column(
            "kitchen_status",
            sa.Enum(
                "QUEUED",
                "COOKING",
                "READY",
                "SERVED",
                "CANCELLED",
                name="kitchen_status",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "order_lines", sa.Column("sent_to_kitchen_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "order_lines", sa.Column("cooking_started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("order_lines", sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("order_lines", sa.Column("served_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        "ix_order_lines_kitchen_queue",
        "order_lines",
        ["kitchen_station", "kitchen_status", "sent_to_kitchen_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_order_lines_kitchen_queue", table_name="order_lines")
    op.drop_column("order_lines", "served_at")
    op.drop_column("order_lines", "ready_at")
    op.drop_column("order_lines", "cooking_started_at")
    op.drop_column("order_lines", "sent_to_kitchen_at")
    op.drop_column("order_lines", "kitchen_status")
    op.drop_column("order_lines", "kitchen_station")
    op.drop_index(op.f("ix_walk_in_queue_tenant_id"), table_name="walk_in_queue")
    op.drop_index(op.f("ix_walk_in_queue_store_id"), table_name="walk_in_queue")
    op.drop_index(op.f("ix_walk_in_queue_customer_id"), table_name="walk_in_queue")
    op.drop_index("ix_queue_store_status", table_name="walk_in_queue")
    op.drop_table("walk_in_queue")
    op.drop_index(op.f("ix_reservations_tenant_id"), table_name="reservations")
    op.drop_index("ix_reservations_store_time", table_name="reservations")
    op.drop_index(op.f("ix_reservations_store_id"), table_name="reservations")
    op.drop_index("ix_reservations_status_time", table_name="reservations")
    op.drop_index(op.f("ix_reservations_reserved_for"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_customer_id"), table_name="reservations")
    op.drop_table("reservations")
    # ### end Alembic commands ###
