"""discount rules and order discount rule link

Revision ID: 94c59eb86478
Revises: f6f425fab90a
Create Date: 2026-07-15 11:29:06.878487+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94c59eb86478"
down_revision: str | Sequence[str] | None = "f6f425fab90a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "PERCENT",
                "AMOUNT",
                "COMP",
                "ALLOWANCE",
                "EMPLOYEE",
                name="order_discount_kind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("min_subtotal", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discount_rules_store_id"), "discount_rules", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_discount_rules_tenant_id"), "discount_rules", ["tenant_id"], unique=False
    )
    op.add_column("order_discounts", sa.Column("rule_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_order_discounts_rule_id_discount_rules",
        "order_discounts",
        "discount_rules",
        ["rule_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_order_discounts_rule_id_discount_rules", "order_discounts", type_="foreignkey"
    )
    op.drop_column("order_discounts", "rule_id")
    op.drop_index(op.f("ix_discount_rules_tenant_id"), table_name="discount_rules")
    op.drop_index(op.f("ix_discount_rules_store_id"), table_name="discount_rules")
    op.drop_table("discount_rules")
    # ### end Alembic commands ###
