"""phase1 closed loop: audit, customers, cash, embeddings, food safety, invoice lifecycle

Revision ID: 6c120a022a19
Revises: ad22105850f7
Create Date: 2026-05-27 06:22:17.345785+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c120a022a19"
down_revision: str | Sequence[str] | None = "ad22105850f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ─── Pre-flight: required extensions ─────────────────────────────
    # pgvector for the embeddings table; citext for the case-insensitive
    # customer phone/email columns created just below. BOTH are required — a
    # fresh Postgres (e.g. a re-provisioned Render free DB) ships with neither,
    # and without citext the ``customers`` CREATE TABLE fails ("type citext does
    # not exist"), aborting the whole migration chain so no tables get built.
    # Safe to re-run (IF NOT EXISTS).
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("phone", postgresql.CITEXT(), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("line_user_id", sa.String(length=64), nullable=True),
        sa.Column("birthdate", sa.Date(), nullable=True),
        sa.Column(
            "tier",
            sa.Enum(
                "REGULAR",
                "SILVER",
                "GOLD",
                "PLATINUM",
                name="customer_tier",
                native_enum=False,
                length=16,
            ),
            server_default="regular",
            nullable=False,
        ),
        sa.Column(
            "points_balance", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "lifetime_value", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("last_visit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    op.create_index(
        "ix_customers_tenant_last_visit", "customers", ["tenant_id", "last_visit_at"], unique=False
    )
    op.create_index("ix_customers_tenant_tier", "customers", ["tenant_id", "tier"], unique=False)
    op.create_index(
        "uq_customers_email",
        "customers",
        ["tenant_id", "email"],
        unique=True,
        postgresql_where="email IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_index(
        "uq_customers_line",
        "customers",
        ["tenant_id", "line_user_id"],
        unique=True,
        postgresql_where="line_user_id IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_index(
        "uq_customers_phone",
        "customers",
        ["tenant_id", "phone"],
        unique=True,
        postgresql_where="phone IS NOT NULL AND deleted_at IS NULL",
    )
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("source_text", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_embeddings_tenant_id"), "embeddings", ["tenant_id"], unique=False)
    op.create_index(
        "ix_embeddings_type_time", "embeddings", ["entity_type", "created_at"], unique=False
    )
    op.create_index(
        "ix_embeddings_vector",
        "embeddings",
        ["vector"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.create_index(
        "uq_embeddings_entity_model",
        "embeddings",
        ["tenant_id", "entity_type", "entity_id", "model_name", "model_version"],
        unique=True,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_table", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        "ix_audit_log_action_time", "audit_log", ["action", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_log_store_id"), "audit_log", ["store_id"], unique=False)
    op.create_index(
        "ix_audit_log_store_time", "audit_log", ["store_id", "occurred_at"], unique=False
    )
    op.create_index("ix_audit_log_target", "audit_log", ["target_table", "target_id"], unique=False)
    op.create_index(op.f("ix_audit_log_tenant_id"), "audit_log", ["tenant_id"], unique=False)
    op.create_table(
        "cash_drawer_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column(
            "register_no",
            sa.Text(),
            nullable=True,
            comment="Physical register identifier if the store has multiple drawers.",
        ),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_by", sa.UUID(), nullable=False),
        sa.Column("closed_by", sa.UUID(), nullable=True),
        sa.Column(
            "opening_float", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("expected_close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("closing_actual", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "variance",
            sa.Numeric(precision=14, scale=4),
            sa.Computed("closing_actual - expected_close", persisted=True),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["closed_by"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["opened_by"], ["employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cash_drawer_sessions_store_id"), "cash_drawer_sessions", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_cash_drawer_sessions_tenant_id"),
        "cash_drawer_sessions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_cash_sessions_store_open",
        "cash_drawer_sessions",
        ["store_id", "opened_at"],
        unique=False,
    )
    op.create_index(
        "uq_cash_sessions_active",
        "cash_drawer_sessions",
        ["store_id", "register_no"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.create_table(
        "customer_points_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("delta", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("source_order_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_points_ledger_customer_id"),
        "customer_points_ledger",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_points_ledger_source_order_id"),
        "customer_points_ledger",
        ["source_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_points_ledger_tenant_id"),
        "customer_points_ledger",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_points_customer_time",
        "customer_points_ledger",
        ["customer_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_points_reason", "customer_points_ledger", ["reason"], unique=False)
    op.add_column("ingredients", sa.Column("lot_no", sa.String(length=64), nullable=True))
    op.add_column("ingredients", sa.Column("expiry_date", sa.Date(), nullable=True))
    op.create_index(
        op.f("ix_ingredients_expiry_date"), "ingredients", ["expiry_date"], unique=False
    )
    op.create_index(op.f("ix_ingredients_lot_no"), "ingredients", ["lot_no"], unique=False)
    op.add_column(
        "menu_items",
        sa.Column(
            "allergens",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "invoice_status",
            sa.Enum(
                "PENDING",
                "ISSUED",
                "VOIDED",
                "ALLOWANCE",
                "WINNER",
                "REDEEMED",
                name="invoice_status",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "invoice_media",
            sa.Enum("CLOUD", "PAPER", name="invoice_media", native_enum=False, length=8),
            nullable=True,
        ),
    )
    op.add_column("orders", sa.Column("void_invoice_number", sa.Text(), nullable=True))
    op.add_column("orders", sa.Column("allowance_invoice_number", sa.Text(), nullable=True))
    op.add_column("stock_movements", sa.Column("lot_no", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_stock_movements_lot_no"), "stock_movements", ["lot_no"], unique=False)
    # ### end Alembic commands ###

    # ─── Append-only enforcement (DB-level, defense-in-depth) ──────────
    # Both ``stock_movements`` and the new ``audit_log`` /
    # ``customer_points_ledger`` are ledger tables. The ORM docstrings
    # say "don't UPDATE or DELETE" but until now nothing actually stopped
    # a careless ``psql`` session (or a buggy DevSwarm-generated module)
    # from rewriting history.
    #
    # ``INSTEAD NOTHING`` rules silently drop UPDATE/DELETE attempts. We
    # use INSTEAD NOTHING (not RAISE EXCEPTION) so a legacy app that
    # blindly issues an UPDATE doesn't crash — but it also has no effect.
    # ROW_COUNT will be 0 so audit-aware callers can detect it.
    for table in ("stock_movements", "audit_log", "customer_points_ledger"):
        op.execute(
            f"CREATE RULE no_update_{table} AS ON UPDATE TO {table} DO INSTEAD NOTHING"
        )
        op.execute(
            f"CREATE RULE no_delete_{table} AS ON DELETE TO {table} DO INSTEAD NOTHING"
        )


def downgrade() -> None:
    # Drop the append-only rules first so the subsequent table drops aren't
    # blocked by their dependency on the rule.
    for table in ("stock_movements", "audit_log", "customer_points_ledger"):
        op.execute(f"DROP RULE IF EXISTS no_update_{table} ON {table}")
        op.execute(f"DROP RULE IF EXISTS no_delete_{table} ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_movements_lot_no"), table_name="stock_movements")
    op.drop_column("stock_movements", "lot_no")
    op.drop_column("orders", "allowance_invoice_number")
    op.drop_column("orders", "void_invoice_number")
    op.drop_column("orders", "invoice_media")
    op.drop_column("orders", "invoice_status")
    op.drop_column("menu_items", "allergens")
    op.drop_index(op.f("ix_ingredients_lot_no"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_expiry_date"), table_name="ingredients")
    op.drop_column("ingredients", "expiry_date")
    op.drop_column("ingredients", "lot_no")
    op.drop_index("ix_points_reason", table_name="customer_points_ledger")
    op.drop_index("ix_points_customer_time", table_name="customer_points_ledger")
    op.drop_index(op.f("ix_customer_points_ledger_tenant_id"), table_name="customer_points_ledger")
    op.drop_index(
        op.f("ix_customer_points_ledger_source_order_id"), table_name="customer_points_ledger"
    )
    op.drop_index(
        op.f("ix_customer_points_ledger_customer_id"), table_name="customer_points_ledger"
    )
    op.drop_table("customer_points_ledger")
    op.drop_index(
        "uq_cash_sessions_active",
        table_name="cash_drawer_sessions",
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.drop_index("ix_cash_sessions_store_open", table_name="cash_drawer_sessions")
    op.drop_index(op.f("ix_cash_drawer_sessions_tenant_id"), table_name="cash_drawer_sessions")
    op.drop_index(op.f("ix_cash_drawer_sessions_store_id"), table_name="cash_drawer_sessions")
    op.drop_table("cash_drawer_sessions")
    op.drop_index(op.f("ix_audit_log_tenant_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_target", table_name="audit_log")
    op.drop_index("ix_audit_log_store_time", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_store_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_action_time", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("uq_embeddings_entity_model", table_name="embeddings")
    op.drop_index(
        "ix_embeddings_vector",
        table_name="embeddings",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.drop_index("ix_embeddings_type_time", table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_tenant_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(
        "uq_customers_phone",
        table_name="customers",
        postgresql_where="phone IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index(
        "uq_customers_line",
        table_name="customers",
        postgresql_where="line_user_id IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index(
        "uq_customers_email",
        table_name="customers",
        postgresql_where="email IS NOT NULL AND deleted_at IS NULL",
    )
    op.drop_index("ix_customers_tenant_tier", table_name="customers")
    op.drop_index("ix_customers_tenant_last_visit", table_name="customers")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
