"""stored value wallet

Revision ID: 9511ce867866
Revises: a1c4f7e2b9d3
Create Date: 2026-06-19 21:36:42.023650+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9511ce867866"
down_revision: str | Sequence[str] | None = "a1c4f7e2b9d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_stored_value_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("delta", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("source_order_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_stored_value_ledger_customer_id"),
        "customer_stored_value_ledger",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_stored_value_ledger_source_order_id"),
        "customer_stored_value_ledger",
        ["source_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_stored_value_ledger_tenant_id"),
        "customer_stored_value_ledger",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_stored_value_customer_time",
        "customer_stored_value_ledger",
        ["customer_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_stored_value_reason", "customer_stored_value_ledger", ["reason"], unique=False
    )
    op.add_column(
        "customers",
        sa.Column(
            "stored_value_balance",
            sa.Numeric(precision=14, scale=4),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    # Append-only discipline — block UPDATE/DELETE at the DB level, same as the
    # points ledger / stock_movements / audit_log. Corrections are new rows.
    _t = "customer_stored_value_ledger"
    op.execute(f"CREATE RULE no_update_{_t} AS ON UPDATE TO {_t} DO INSTEAD NOTHING")
    op.execute(f"CREATE RULE no_delete_{_t} AS ON DELETE TO {_t} DO INSTEAD NOTHING")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _t = "customer_stored_value_ledger"
    op.execute(f"DROP RULE IF EXISTS no_update_{_t} ON {_t}")
    op.execute(f"DROP RULE IF EXISTS no_delete_{_t} ON {_t}")
    op.drop_column("customers", "stored_value_balance")
    op.drop_index("ix_stored_value_reason", table_name="customer_stored_value_ledger")
    op.drop_index("ix_stored_value_customer_time", table_name="customer_stored_value_ledger")
    op.drop_index(
        op.f("ix_customer_stored_value_ledger_tenant_id"), table_name="customer_stored_value_ledger"
    )
    op.drop_index(
        op.f("ix_customer_stored_value_ledger_source_order_id"),
        table_name="customer_stored_value_ledger",
    )
    op.drop_index(
        op.f("ix_customer_stored_value_ledger_customer_id"),
        table_name="customer_stored_value_ledger",
    )
    op.drop_table("customer_stored_value_ledger")
    # ### end Alembic commands ###
