"""add_public_holidays_table

Revision ID: 0b230fe61411
Revises: de4a293237b8
Create Date: 2026-06-05 14:09:29.136031+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b230fe61411"
down_revision: str | Sequence[str] | None = "de4a293237b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_holidays",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=2), server_default="TW", nullable=False),
        sa.Column("holiday_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_public_holidays_country_date",
        "public_holidays",
        ["country", "holiday_date"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_public_holidays_country_date", table_name="public_holidays")
    op.drop_table("public_holidays")
    # ### end Alembic commands ###
