"""pickup call board and menu item translations

Revision ID: f6f425fab90a
Revises: 5603cb48bb78
Create Date: 2026-07-14 15:11:28.488965+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6f425fab90a"
down_revision: str | Sequence[str] | None = "5603cb48bb78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "menu_items",
        sa.Column(
            "translations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "orders", sa.Column("pickup_called_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "pickup_called_at")
    op.drop_column("menu_items", "translations")
    # ### end Alembic commands ###
