"""employees pin_hash for POS auth

Revision ID: 87ef29f6e7bb
Revises: 195155ee96df
Create Date: 2026-07-11 01:27:31.258626+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87ef29f6e7bb"
down_revision: str | Sequence[str] | None = "195155ee96df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("pin_hash", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "pin_hash")
    # ### end Alembic commands ###
