"""order_events realtime floor stream

Revision ID: 195155ee96df
Revises: 20b062b46d2c
Create Date: 2026-07-10 17:34:13.370527+08:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "195155ee96df"
down_revision: str | Sequence[str] | None = "20b062b46d2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_index("ix_order_events_store_seq", "order_events", ["store_id", "seq"], unique=False)
    op.create_index(op.f("ix_order_events_tenant_id"), "order_events", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # ─── Append-only enforcement (DB-level, defense-in-depth) ──────────
    # order_events is the real-time floor ledger. Like stock_movements /
    # audit_log / customer_points_ledger, history must never be rewritten:
    # a reconnecting tablet replays by seq cursor and trusts that a seq it
    # already saw can't have changed under it. ``INSTEAD NOTHING`` silently
    # drops any UPDATE/DELETE (ROW_COUNT 0) so a careless caller can't
    # mutate the stream.
    op.execute(
        "CREATE RULE no_update_order_events AS ON UPDATE TO order_events DO INSTEAD NOTHING"
    )
    op.execute(
        "CREATE RULE no_delete_order_events AS ON DELETE TO order_events DO INSTEAD NOTHING"
    )


def downgrade() -> None:
    # Drop the append-only rules first so the table drop isn't blocked by the
    # rules' dependency on it.
    op.execute("DROP RULE IF EXISTS no_update_order_events ON order_events")
    op.execute("DROP RULE IF EXISTS no_delete_order_events ON order_events")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_events_tenant_id"), table_name="order_events")
    op.drop_index("ix_order_events_store_seq", table_name="order_events")
    op.drop_table("order_events")
    # ### end Alembic commands ###
