"""Daily brief cron tests — 17 acceptance criteria from
``specs/daily_brief_cron.md`` §11.

All tests inject FakeLLMClient + FakeRetrievalClient + NullSink /
tmp_path FileSink, so the pipeline never touches the network or writes
outside the pytest sandbox.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from restaurant_api.jobs import (
    run_engineering_gaps,
    run_investor_qa_prep,
    run_today_top5,
    run_weekly_review,
)
from restaurant_api.jobs._brief_prompts import (
    _VERSION_MAP,
    FORBIDDEN_WORDS,
    resolve_template,
)
from restaurant_api.jobs._brief_sinks import (
    BriefSinkError,
    FileSink,
    NullSink,
)
from restaurant_api.jobs.daily_brief import (
    FakeLLMClient,
    FakeRetrievalClient,
    RetrievedChunk,
    _business_date,
)
from restaurant_api.models import AuditLog, BriefRun, KnowledgeQuery, Tenant

pytestmark = pytest.mark.asyncio

TPE = ZoneInfo("Asia/Taipei")


# ─── helpers ──────────────────────────────────────────────────────────


def _hits(n: int = 3) -> list[RetrievedChunk]:
    return [
        RetrievedChunk(
            chunk_id=uuid.uuid4(),
            document_id=uuid.uuid4(),
            text=f"chunk-{i} 內容 {i}",
            score=0.9 - i * 0.05,
            section_path=f"Section > Sub {i}",
        )
        for i in range(n)
    ]


def _fake_llm(text: str = "# BRIEF\n\nTL;DR: ok\n\n- item 1") -> FakeLLMClient:
    return FakeLLMClient(reply=text)


def _fake_retrieval(hits: list[RetrievedChunk] | None = None) -> FakeRetrievalClient:
    return FakeRetrievalClient(chunks=list(hits) if hits is not None else _hits(3))


def _now_tpe(y: int, m: int, d: int, h: int = 9) -> datetime:
    return datetime(y, m, d, h, 0, 0, tzinfo=TPE).astimezone(UTC)


# ─── AC-1 · today_top5 happy path ────────────────────────────────────


async def test_daily_brief_ac_01_happy_path(
    db_session: AsyncSession, seed_tenant: Tenant, tmp_path: Path
) -> None:
    result = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=FileSink("MORNING_BRIEF.md", repo_root=tmp_path),
        retrieval=_fake_retrieval(),
        llm=_fake_llm("# 今日重點\n\nTL;DR: X"),
        tenant_id=seed_tenant.id,
    )
    assert result.status == "completed"
    row = (
        await db_session.execute(select(BriefRun).where(BriefRun.id == result.brief_run_id))
    ).scalar_one()
    assert row.brief_kind == "today_top5"
    assert row.output_path == "MORNING_BRIEF.md"

    on_disk = (tmp_path / "MORNING_BRIEF.md").read_text(encoding="utf-8")
    assert "auto-generated by daily_brief.today_top5" in on_disk
    assert "# 今日重點" in on_disk


# ─── AC-2 · idempotent on same day + same prompt version ──────────────


async def test_daily_brief_ac_02_idempotent(
    db_session: AsyncSession, seed_tenant: Tenant, tmp_path: Path
) -> None:
    llm = _fake_llm()
    retr = _fake_retrieval()
    kw = dict(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=retr,
        llm=llm,
        tenant_id=seed_tenant.id,
    )
    first = await run_today_top5(**kw)
    second = await run_today_top5(**kw)
    assert first.status == "completed"
    assert second.status == "skipped_duplicate"
    assert second.brief_run_id == first.brief_run_id
    # LLM called exactly once
    assert len(llm.calls) == 1


# ─── AC-3 · prompt bump triggers re-run ──────────────────────────────


async def test_daily_brief_ac_03_prompt_bump_reruns(
    db_session: AsyncSession, seed_tenant: Tenant, monkeypatch
) -> None:
    llm = _fake_llm()
    retr = _fake_retrieval()
    kw = dict(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=retr,
        llm=llm,
        tenant_id=seed_tenant.id,
    )
    first = await run_today_top5(**kw)
    assert first.status == "completed"

    # Bump the prompt version — simulate a v1 → v2 revision.
    monkeypatch.setitem(
        _VERSION_MAP,
        "today_top5",
        ("today_top5/v2", _VERSION_MAP["today_top5"][1] + "\n\nv2 tweak"),
    )
    second = await run_today_top5(**kw)
    assert second.status == "completed"
    assert second.prompt_template_version == "today_top5/v2"
    assert second.brief_run_id != first.brief_run_id
    assert len(llm.calls) == 2


# ─── AC-4 · empty KB writes graceful placeholder, no LLM call ────────


async def test_daily_brief_ac_04_empty_kb(
    db_session: AsyncSession, seed_tenant: Tenant, tmp_path: Path
) -> None:
    llm = _fake_llm()
    result = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=FileSink("MORNING_BRIEF.md", repo_root=tmp_path),
        retrieval=_fake_retrieval(hits=[]),  # empty KB
        llm=llm,
        tenant_id=seed_tenant.id,
    )
    assert result.status == "skipped_empty_kb"
    assert llm.calls == []  # LLM not called
    text = (tmp_path / "MORNING_BRIEF.md").read_text(encoding="utf-8")
    assert "尚無資料" in text


# ─── AC-5 · failure then retry updates same row ──────────────────────


async def test_daily_brief_ac_05_failure_then_retry(
    db_session: AsyncSession, seed_tenant: Tenant, tmp_path: Path
) -> None:
    llm_bad = FakeLLMClient(fail_on_call=1)
    first = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=llm_bad,
        tenant_id=seed_tenant.id,
    )
    assert first.status == "failed"
    assert first.error_message and "LLM boom" in first.error_message

    # Retry same day same prompt version — should update the same row.
    llm_ok = _fake_llm()
    second = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=llm_ok,
        tenant_id=seed_tenant.id,
    )
    assert second.status == "completed"
    assert second.brief_run_id == first.brief_run_id

    rows = (
        await db_session.execute(
            select(BriefRun).where(BriefRun.tenant_id == seed_tenant.id)
        )
    ).scalars().all()
    assert len(rows) == 1


# ─── AC-6 · engineering_gaps scope filter ────────────────────────────


async def test_daily_brief_ac_06_engineering_scope_filter(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    retr = _fake_retrieval()
    result = await run_engineering_gaps(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 18),
        sink=NullSink(),
        retrieval=retr,
        llm=_fake_llm("| 項目 | 已報價 | 缺項 | 該問誰 |\n|---|---|---|---|"),
        tenant_id=seed_tenant.id,
    )
    assert result.status == "completed"
    # The retrieval call must have been scoped to engineering only.
    assert retr.calls[-1]["scopes"] == ["engineering"]


# ─── AC-7 · investor_qa_prep business_date is what tpe date says ─────


async def test_daily_brief_ac_07_investor_business_date(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    # Monday 2026-06-29 09:00 Taipei
    result = await run_investor_qa_prep(
        session=db_session,
        now=_now_tpe(2026, 6, 29, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=_fake_llm(),
        tenant_id=seed_tenant.id,
    )
    assert result.business_date.isoformat() == "2026-06-29"


# ─── AC-8 · weekly_review anchors to Friday even if misfired Sat ─────


def test_daily_brief_ac_08_weekly_review_friday_anchor() -> None:
    fri = _business_date("weekly_review", _now_tpe(2026, 6, 26, 17))  # Fri
    sat = _business_date("weekly_review", _now_tpe(2026, 6, 27, 9))  # Sat (misfire)
    thu = _business_date("weekly_review", _now_tpe(2026, 6, 25, 17))  # Thu (early)
    assert fri.isoformat() == "2026-06-26"
    assert sat.isoformat() == "2026-06-26"  # rolled BACK to Friday
    assert thu.isoformat() == "2026-06-26"  # rolled FORWARD to Friday


# ─── AC-9 · weekly_review prompt contains audit summary placeholder ──


async def test_daily_brief_ac_09_weekly_review_prompt_shape(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    llm = _fake_llm()
    await run_weekly_review(
        session=db_session,
        now=_now_tpe(2026, 6, 26, 17),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=llm,
        tenant_id=seed_tenant.id,
    )
    assert llm.calls, "LLM must have been called"
    user_prompt = llm.calls[-1]["user"]
    assert "audit_log" in user_prompt or "本週" in user_prompt


# ─── AC-10 · FileSink atomic — no leftover .tmp on write failure ─────


async def test_daily_brief_ac_10_filesink_write_failure(
    db_session: AsyncSession, seed_tenant: Tenant, tmp_path: Path, monkeypatch
) -> None:
    sink = FileSink("MORNING_BRIEF.md", repo_root=tmp_path)

    def _boom(*_a, **_k):
        raise OSError("disk full")

    monkeypatch.setattr("os.replace", _boom)

    with pytest.raises(BriefSinkError):
        await run_today_top5(
            session=db_session,
            now=_now_tpe(2026, 6, 27, 9),
            sink=sink,
            retrieval=_fake_retrieval(),
            llm=_fake_llm(),
            tenant_id=seed_tenant.id,
        )
    # No lingering .tmp file
    leftovers = list(tmp_path.glob("*.tmp"))
    assert leftovers == []


# ─── AC-11 · FileSink refuses path escape ────────────────────────────


def test_daily_brief_ac_11_path_escape_rejected(tmp_path: Path) -> None:
    with pytest.raises(BriefSinkError):
        FileSink("../etc/passwd", repo_root=tmp_path)


# ─── AC-12 · NullSink works, output_path is None ─────────────────────


async def test_daily_brief_ac_12_null_sink(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    result = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=_fake_llm("# BR\n\ncontent"),
        tenant_id=seed_tenant.id,
    )
    assert result.output_path is None
    row = (
        await db_session.execute(
            select(BriefRun).where(BriefRun.id == result.brief_run_id)
        )
    ).scalar_one()
    assert row.output_path is None
    assert row.output_markdown is not None
    assert "content" in row.output_markdown


# ─── AC-13 · audit_log row written ───────────────────────────────────


async def test_daily_brief_ac_13_audit_log_written(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    result = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=_fake_llm(),
        tenant_id=seed_tenant.id,
    )
    row = (
        await db_session.execute(
            select(AuditLog).where(
                AuditLog.action == "brief.completed",
                AuditLog.target_id == result.brief_run_id,
            )
        )
    ).scalar_one()
    assert row.target_table == "brief_runs"
    assert row.after and row.after["brief_kind"] == "today_top5"


# ─── AC-14 · retrieval audit row written ─────────────────────────────


async def test_daily_brief_ac_14_retrieval_audit_written(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(_hits(4)),
        llm=_fake_llm(),
        tenant_id=seed_tenant.id,
    )
    q = (
        await db_session.execute(
            select(KnowledgeQuery).where(
                KnowledgeQuery.tenant_id == seed_tenant.id,
                KnowledgeQuery.actor_kind == "cron",
                KnowledgeQuery.actor_id == "daily_brief.today_top5",
            )
        )
    ).scalar_one()
    assert q.retrieved_chunk_ids and len(q.retrieved_chunk_ids) == 4


# ─── AC-15 · scheduler registers 4 brief jobs ────────────────────────


def test_daily_brief_ac_15_scheduler_registers_all() -> None:
    from apscheduler.schedulers.asyncio import AsyncIOScheduler

    from restaurant_api.jobs import _register

    scheduler = AsyncIOScheduler()
    _register(scheduler)
    ids = {j.id for j in scheduler.get_jobs()}
    for jid in ("today_top5", "engineering_gaps", "investor_qa_prep", "weekly_review"):
        assert jid in ids, f"scheduler missing {jid}"


# ─── AC-16 · no external HTTP calls made by any brief ─────────────────


async def test_daily_brief_ac_16_no_external_http(
    db_session: AsyncSession, seed_tenant: Tenant, monkeypatch
) -> None:
    """Guard against a future 'nice-to-have' Notion/Slack sink getting
    silently smuggled into the pipeline."""
    constructed: list[str] = []
    import httpx

    class _Sentinel(httpx.AsyncClient):
        def __init__(self, *a, **k):  # type: ignore[no-untyped-def]
            constructed.append("httpx.AsyncClient built")
            super().__init__(*a, **k)

    monkeypatch.setattr(httpx, "AsyncClient", _Sentinel)

    await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=_fake_llm(),
        tenant_id=seed_tenant.id,
    )
    assert constructed == []


# ─── AC-17 · forbidden words flagged in meta, but do not block ───────


async def test_daily_brief_ac_17_forbidden_words_flagged(
    db_session: AsyncSession, seed_tenant: Tenant
) -> None:
    # Choose a real word from the list so the tests + spec stay in sync.
    tainted = f"# BR\n\n{FORBIDDEN_WORDS[0]} tasting notes 網美"
    result = await run_today_top5(
        session=db_session,
        now=_now_tpe(2026, 6, 27, 9),
        sink=NullSink(),
        retrieval=_fake_retrieval(),
        llm=_fake_llm(tainted),
        tenant_id=seed_tenant.id,
    )
    assert result.status == "completed"  # NOT blocked
    row = (
        await db_session.execute(
            select(BriefRun).where(BriefRun.id == result.brief_run_id)
        )
    ).scalar_one()
    assert row.meta.get("forbidden_words")
    assert FORBIDDEN_WORDS[0] in row.meta["forbidden_words"]


# ─── extras: prompt template shape smoke ─────────────────────────────


def test_prompt_versions_are_v1() -> None:
    for kind in (
        "today_top5",
        "engineering_gaps",
        "investor_qa_prep",
        "weekly_review",
    ):
        ver, tpl = resolve_template(kind)
        assert ver.endswith("/v1")
        assert tpl.strip()
        assert "{corpus}" in tpl or "chunk" in tpl
