"""Sinks for daily-brief output.

Only ``FileSink`` and ``NullSink`` in this slice — Notion / Drive / Email
adapters live in a follow-up spec.

``FileSink`` writes atomically (``<path>.tmp`` → ``os.replace``) and
refuses paths that escape the repo root — the spec is strict about
never letting a template variable land outside the repo.
"""

from __future__ import annotations

import contextlib
import os
from datetime import UTC, datetime
from pathlib import Path
from typing import Protocol

from fastapi import status

from restaurant_api.api.errors import DomainError


class BriefSinkError(DomainError):
    code = "BRIEF_SINK_ERROR"
    status_code = status.HTTP_500_INTERNAL_SERVER_ERROR


class BriefSink(Protocol):
    """Persist a rendered brief. Returns the resolved output path or None."""

    async def write(self, *, kind: str, markdown: str) -> str | None:
        ...  # pragma: no cover — Protocol


class FileSink:
    """Write to a repo-relative path atomically. Overwrites on every run."""

    def __init__(
        self,
        repo_relative_path: str,
        *,
        repo_root: Path | None = None,
    ) -> None:
        root = (repo_root or Path.cwd()).resolve()
        target = (root / repo_relative_path).resolve()
        try:
            target.relative_to(root)
        except ValueError as exc:
            raise BriefSinkError(
                f"path escapes repo root: {repo_relative_path!r}"
            ) from exc
        self._root = root
        self._target = target

    async def write(self, *, kind: str, markdown: str) -> str:
        self._target.parent.mkdir(parents=True, exist_ok=True)
        header = (
            f"<!-- auto-generated by daily_brief.{kind} at "
            f"{datetime.now(UTC).isoformat(timespec='seconds')} -->\n\n"
        )
        tmp = self._target.with_suffix(self._target.suffix + ".tmp")
        try:
            tmp.write_text(header + markdown, encoding="utf-8")
            os.replace(tmp, self._target)
        except OSError as exc:
            with contextlib.suppress(OSError):
                tmp.unlink()
            raise BriefSinkError(f"file write failed: {exc}") from exc
        # Return path relative to repo root when possible.
        try:
            rel = self._target.relative_to(self._root)
            return str(rel)
        except ValueError:
            return str(self._target)


class NullSink:
    """No-op sink for dry runs and tests."""

    async def write(self, *, kind: str, markdown: str) -> None:
        return None


__all__ = ["BriefSink", "BriefSinkError", "FileSink", "NullSink"]
